# Generated by Django 3.0.4 on 2020-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=25)),
                ('name_middle', models.CharField(blank=True, max_length=25)),
                ('name_last', models.CharField(max_length=50)),
                ('dancer_type', models.CharField(choices=[('PRO', 'Professional'), ('PAS', 'Pro-Am Student'), ('JRS', 'Junior Pro-Am Student'), ('AAM', 'Amateur'), ('JAM', 'Junior Amateur')], default='PRO', max_length=3)),
            ],
        ),
    ]
