# Generated by Django 3.0.4 on 2020-03-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_type', models.CharField(choices=[('PRC', 'Professional Couple'), ('PAC', 'Pro-Am Couple'), ('JPC', 'Junior Pro-Am Couple'), ('AMC', 'Amateur Couple'), ('JAC', 'Junior Amateur Couple')], default='PAC', max_length=3)),
            ],
        ),
    ]
