# Generated by Django 3.0.4 on 2020-04-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20200401_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='dancer_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_or_student', to='rankings.Dancer'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='dancer_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_or_instructor', to='rankings.Dancer'),
        ),
    ]
