# Generated by Django 3.0.4 on 2020-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20200401_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='dancer_type',
            field=models.CharField(choices=[('PRO', 'Professional'), ('PAS', 'Pro-Am Student'), ('JRS', 'Junior Pro-Am Student'), ('AM', 'Amateur'), ('JR', 'Junior Amateur')], default='PRO', max_length=3),
        ),
    ]
