# Generated by Django 3.0.4 on 2020-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200414_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='event_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couple',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='couple',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
