# Generated by Django 3.0.4 on 2020-10-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20200516_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dancer',
            options={'ordering': ['name_last', 'name_first']},
        ),
    ]
