# Generated by Django 3.1.4 on 2021-11-07 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_auto_20201030_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='name_fix_date',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
    ]
