# Generated by Django 4.0.4 on 2022-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_auto_20211126_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='elo_rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
