# Generated by Django 4.0.4 on 2022-07-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0012_couple_elo_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='elo_rating',
        ),
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('SMOO', 'Smooth'), ('RHY', 'Rhythm'), ('STD', 'Standard'), ('LAT', 'Latin'), ('CAB', 'Cabaret-Theater_Arts'), ('NC', 'Nightclub'), ('CTRY', 'Country_Western'), ('MIX', 'Combined'), ('UNK', 'Unknown')], default='UNK', max_length=4)),
                ('value', models.FloatField(default=None, null=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.couple')),
            ],
        ),
    ]
