# Generated by Django 4.0.4 on 2022-08-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0014_alter_couple_id_alter_dancer_id_alter_elorating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='elorating',
            name='num_events',
            field=models.IntegerField(default=0),
        ),
    ]
