# Generated by Django 4.0.4 on 2022-08-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_elorating_num_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elorating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
