# Generated by Django 4.0.4 on 2022-08-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0016_alter_couple_id_alter_dancer_id_alter_elorating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='couple_type',
            field=models.CharField(choices=[('PRC', 'Professional'), ('PAC', 'Pro-Am'), ('JPC', 'Junior Pro-Am'), ('AMC', 'Amateur'), ('JAC', 'Junior Amateur')], default='PAC', max_length=3),
        ),
        migrations.AlterField(
            model_name='couple',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elorating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
