# Generated by Django 3.0.4 on 2020-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_comp_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='url_data_format',
            field=models.CharField(choices=[('CM', 'Comp Manager'), ('CO', 'Comp Organizer'), ('ND', 'NDCA Premier')], default='CM', max_length=2),
        ),
    ]
