# Generated by Django 3.0.4 on 2020-04-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_comp_url_data_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_number', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('points', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PH', 'Pro heat'), ('NH', 'Heat')], default='NH', max_length=2)),
                ('heat_number', models.IntegerField()),
                ('extra', models.CharField(blank=True, max_length=20)),
                ('info', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('SMOO', 'Smooth'), ('RHY', 'Rhythm'), ('STD', 'Standard'), ('LAT', 'Latin'), ('CAB', 'Cabaret / Theater Arts'), ('NC', 'Night Club'), ('CTRY', 'Country Western'), ('MIX', 'Combined'), ('UNK', 'Unknown')], default='UNK', max_length=4)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('time', models.DateTimeField(blank=True)),
                ('rounds', models.CharField(default='F', max_length=20)),
                ('base_value', models.IntegerField(blank=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.Comp')),
            ],
        ),
    ]
