# Generated by Django 3.0.4 on 2020-04-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200414_0150'),
        ('comps', '0004_heat_heatresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompMngrDancer',
            fields=[
                ('dancer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rankings.Dancer')),
            ],
            bases=('rankings.dancer',),
        ),
    ]
