# Generated by Django 3.0.4 on 2020-04-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200414_0150'),
        ('comps', '0006_auto_20200418_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatresult',
            name='couple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.Couple'),
        ),
        migrations.AddField(
            model_name='heatresult',
            name='heat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.Heat'),
        ),
    ]
