# Generated by Django 3.0.4 on 2020-04-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_auto_20200418_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatresult',
            name='heat',
        ),
    ]
