# Generated by Django 3.0.4 on 2020-04-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0008_remove_heatresult_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatresult',
            name='heat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.Heat'),
        ),
    ]
