# Generated by Django 3.0.4 on 2020-04-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200414_0150'),
        ('comps', '0009_heatresult_heat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeatResult',
            new_name='HeatEntry',
        ),
    ]
