# Generated by Django 3.0.4 on 2020-04-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200414_0150'),
        ('comps', '0010_auto_20200421_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatlistDancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CompMngrDancer',
        ),
    ]
