# Generated by Django 3.0.4 on 2020-04-22 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200414_0150'),
        ('comps', '0011_auto_20200421_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedHeatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Couple')),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_1', to='comps.HeatlistDancer')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.HeatEntry')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_2', to='comps.HeatlistDancer')),
            ],
        ),
    ]
