# Generated by Django 3.0.4 on 2020-04-26 14:03

import comps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0014_heatlistdancer_formatting_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='heatsheet_file',
            field=models.FileField(blank=True, upload_to=comps.models.comp_logo_path),
        ),
    ]
