# Generated by Django 3.0.4 on 2020-04-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0015_comp_heatsheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='process_state',
            field=models.IntegerField(choices=[(1, 'Initial'), (2, 'Dancers Loaded'), (3, 'Dancer Names Formatted'), (4, 'Heats Loaded'), (5, 'Heat Styles Defined'), (6, 'Heat Levels Defined'), (7, 'Couples Matched'), (8, 'Scoresheets Loaded'), (9, 'Results Resolved'), (10, 'Complete')], default=1),
        ),
    ]
