# Generated by Django 3.0.4 on 2020-04-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0016_comp_process_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='process_state',
            field=models.CharField(choices=[('IN', 'Initial'), ('DL', 'Dancers Loaded'), ('DNF', 'Dancer Names Formatted'), ('HL', 'Heats Loaded'), ('HSD', 'Heat Styles Defined'), ('HLD', 'Heat Levels Defined'), ('CEM', 'Heat Entries Matched'), ('SSL', 'Scoresheets Loaded'), ('RR', 'Results Resolved'), ('FIN', 'Complete')], default='IN', max_length=3),
        ),
    ]
