# Generated by Django 3.0.4 on 2020-04-30 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0019_auto_20200429_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='process_state',
        ),
    ]
