# Generated by Django 3.0.4 on 2020-04-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0020_remove_comp_process_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='process_state',
            field=models.CharField(choices=[('IN', 'Comp Initialized'), ('DL', 'Dancers Loaded'), ('DNF', 'Dancer Names Formatted'), ('HL', 'Heats Loaded'), ('HSD', 'Heat Levels Defined'), ('CEM', 'Heat Entries Matched'), ('SSL', 'Scoresheets Loaded'), ('RR', 'Results Resolved '), ('FIN', 'Processing Complete')], default='IN', max_length=3),
        ),
    ]
