# Generated by Django 3.0.4 on 2020-05-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0022_auto_20200430_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unmatchedheatentry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='unmatchedheatentry',
            name='couple',
        ),
    ]
