# Generated by Django 3.0.4 on 2020-05-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0023_auto_20200502_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat',
            name='style',
            field=models.CharField(choices=[('SMOO', 'Smooth'), ('RHY', 'Rhythm'), ('STD', 'Standard'), ('LAT', 'Latin'), ('CAB', 'Cabaret-Theater_Arts'), ('NC', 'Nightclub'), ('CTRY', 'Country_Western'), ('MIX', 'Combined'), ('UNK', 'Unknown')], default='UNK', max_length=4),
        ),
    ]
