# Generated by Django 3.0.4 on 2020-05-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20200516_2205'),
        ('comps', '0024_auto_20200516_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeatEntry',
            new_name='Heat_Entry',
        ),
        migrations.RenameModel(
            old_name='HeatlistDancer',
            new_name='Heatlist_Dancer',
        ),
        migrations.RenameModel(
            old_name='UnmatchedHeatEntry',
            new_name='Unmatched_Heat_Entry',
        ),
    ]
