# Generated by Django 3.0.4 on 2020-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0025_auto_20200523_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat',
            name='session',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='heat_entry',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
