# Generated by Django 3.0.4 on 2020-05-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0026_auto_20200523_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heat',
            name='session',
        ),
    ]
