# Generated by Django 3.0.4 on 2020-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0027_remove_heat_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat_entry',
            name='result',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
