# Generated by Django 3.0.4 on 2020-05-30 00:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0028_auto_20200525_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='logo'),
        ),
    ]
