# Generated by Django 3.0.4 on 2020-05-30 00:33

import comps.models.comp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0029_auto_20200530_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='logo',
            field=models.ImageField(blank=True, upload_to=comps.models.comp.comp_logo_path),
        ),
    ]
