# Generated by Django 3.1.4 on 2021-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0039_auto_20201030_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat_entry',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
