# Generated by Django 3.1.4 on 2021-02-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0040_heat_entry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='url_data_format',
            field=models.CharField(choices=[('CM', 'Comp Manager'), ('CO', 'Comp Organizer'), ('ND', 'NDCA Premier'), ('O2', 'O2cm.com')], default='CM', max_length=2),
        ),
    ]
