# Generated by Django 3.1.4 on 2021-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0041_auto_20210220_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='heatsheet_load_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
