# Generated by Django 3.1.4 on 2021-04-23 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_auto_20201030_0311'),
        ('comps', '0042_comp_heatsheet_load_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatlist_dancer',
            name='alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.dancer'),
        ),
        migrations.AddField(
            model_name='heatlist_dancer',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.comp'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='heatsheet_load_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), null=True),
        ),
    ]
