# Generated by Django 3.1.4 on 2021-05-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0044_result_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatlist_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(choices=[('NO_ERR', 'No Error'), ('UNK_LEV', 'Unknown Event Level'), ('UNK_STYL', 'Unknown Event Style'), ('NO_COUNT', 'Heat Count Not Found'), ('NO_COUNT', 'Scoresheet Code Not Found'), ('NO_PRTNR', 'Partner Not Found'), ('PARS_ERR', 'Unable to Parse Heat'), ('BAD_TIME', 'Invalid Heat Time')], default='NO_ERR', max_length=8)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.comp')),
                ('dancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comps.heatlist_dancer')),
                ('heat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comps.heat')),
            ],
        ),
    ]
