# Generated by Django 3.1.4 on 2021-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0045_heatlist_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatlist_error',
            name='dancer',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
