# Generated by Django 3.1.4 on 2021-07-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0047_heat_dance_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat',
            name='category',
            field=models.CharField(choices=[('PH', 'Pro heat'), ('NH', 'Heat'), ('SO', 'Solo'), ('4M', 'Formation')], default='NH', max_length=2),
        ),
    ]
