# Generated by Django 3.1.4 on 2021-11-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0049_auto_20210722_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='url_data_format',
            field=models.CharField(choices=[('CM', 'Comp Manager'), ('CH', 'Comp Manager - Heats'), ('CO', 'Comp Organizer'), ('ND', 'NDCA Premier'), ('NF', 'NDCA Premier - Feed'), ('O2', 'O2cm.com')], default='CM', max_length=2),
        ),
    ]
