# Generated by Django 4.0.4 on 2022-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0055_comp_scoresheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat',
            name='elo_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heat_entry',
            name='elo_adjust',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
