# Generated by Django 4.0.4 on 2022-08-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0056_heat_elo_applied_heat_entry_elo_adjust'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat',
            name='initial_elo_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='url_data_format',
            field=models.CharField(choices=[('CM', 'Comp Manager'), ('CO', 'Comp Organizer'), ('ND', 'NDCA Premier - Old Format'), ('NF', 'NDCA Premier'), ('O2', 'O2cm.com')], default='CM', max_length=2),
        ),
        migrations.AlterField(
            model_name='result_error',
            name='error',
            field=models.CharField(choices=[('NO_ERR', 'No Error'), ('UNK_LEV', 'Unknown Event Level'), ('UNK_STYL', 'Unknown Event Style'), ('UNK_ELO', 'Unknown Initial Elo Value'), ('NO_SCORE', 'Heat Info Not Found'), ('NO_ENT', 'No Entries in Heat'), ('NO_RES', 'No Results Found for Heat'), ('NO_COUPL', 'No Results Found for Couple'), ('TWO_RES', 'Two Results Found for Couple'), ('EARLY_RD', 'Unexpected Early Round'), ('LATE_ENT', 'Late Entry')], default='NO_ERR', max_length=8),
        ),
    ]
