# Generated by Django 4.0.7 on 2022-09-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0059_alter_comp_id_alter_comp_couple_id_alter_heat_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp',
            options={'ordering': ['title']},
        ),
    ]
