# Generated by Django 4.1.4 on 2023-01-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0061_alter_heatlist_dancer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comp_couple',
            options={'ordering': ['comp']},
        ),
    ]
