# Generated by Django 4.1.7 on 2023-05-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0062_alter_comp_couple_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='url_data_format',
            field=models.CharField(choices=[('CM', 'Comp Manager'), ('CO', 'Comp Organizer'), ('DC', 'DanceComp'), ('NF', 'NDCA Premier'), ('O2', 'O2cm.com')], default='CM', max_length=2),
        ),
    ]
